### ISSUE TITLE
Distribution and scanner unit testing

### ISSUE THREAD

**Issue by jshlbrd** [target/strelka#1]
**Is your feature request related to a problem? Please describe.**
At release the project doesn't have unit tests for file distribution or scanners -- since these are some of the most critical parts of the project, we should have some test coverage for them.  

**Describe the solution you'd like**
Unit tests for file distribution and scanners. These can be gradually introduced.

**Describe alternatives you've considered**
The current alternative and expectation is that contributors perform testing and and document the tests before submitting PRs, but given the density of the project, it can be difficult to test every critical component.

**Additional context**
N/A

**Comment by infosec-intern** [comment]
Is there a specific test module or format you want to use for this? 

I added some version_info extraction to the `scan_pe.py` scanner and plan to add a test or two before I PR it. If not, I was just gonna use Python's built-in unittests module

**Comment by infosec-intern** [comment]
I'm working on the same for one of my own repositories. I can give building a full strategy a shot - I just wanted to make sure I wasn't reinventing the wheel here if you already had something in mind

I'll go ahead and add some tests for the rest of the ScanPe components too and figure out what works/doesn't work then.

**Comment by jshlbrd** [comment]
@infosec-intern that's a good idea--let's see how the tests for ScanPe work out and then we can make decisions starting from there.

**Comment by jshlbrd** [comment]
Based on the results of the ScanPe unit testing, I think the best way to move forward may be to start with unit tests for each scanner and the tasting functions. I'll close out this issue and create new ones for each scanner.
