### ISSUE TITLE
next release

### ISSUE THREAD

**Issue by zerstoeren** [target/strelka#127]
Hi Team,

I've been looking at strelka again and noticed it has changed a lot since I looked at it last time.  Before I download and start playing with it, are there any major releases coming up?

Great work!  TIA

**Comment by phutelmyer** [comment]
@zerstoeren You read my mind! I'm putting together a release shortly and I'll tag you when it is ready to go.

**Comment by zerstoeren** [comment]
Perfect.  Thank you very much!  I look forward to see it then.  :)
