### ISSUE TITLE
Use go fmt

### ISSUE THREAD

**Issue by rhaist** [target/strelka#131]
Looking at the Go source code and fixing some minor bugs I noticed that the official go fmt was not used to format the code. As every IDE applies go fmt automatically pull requests will be hard as the resulting git changes are basically every line of the original code.

I recommend either:

1. Running `find . -iname '*.go' -exec gofmt -w {} \;` from the project root once and push.
2. Let me prepare a PR for you with the changes.

Let me know what you think.

**Comment by phutelmyer** [comment]
Good catch. Thanks @rhaist, much appreciated. Implemented and merged.
