### ISSUE TITLE
It appears go-redis update changed the arguments to cd.cmdable.ping

### ISSUE THREAD

**Issue by deathnmind** [target/strelka#136]
**Describe the bug**
While running the docker-compose the manager fails to build with error.

```
# github.com/target/strelka/src/go/cmd/strelka-manager

./main.go:40:19: not enough arguments in call to cd.cmdable.Ping
	have ()
	want (context.Context)
./main.go:46:35: not enough arguments in call to cd.cmdable.ZRemRangeByScore
	have (string, string, string)
	want (context.Context, string, string, string)
```

**Steps to reproduce**
1. Run docker-compose -f build/docker-compose.yaml up -d
2. Scroll to bottom
3. See error fails the docker-compose build sequence

**Expected behavior**
Expect the docker-compose process to complete with built and running strelka containers.

**Additional context**
Go-redis pushed changes 4 days ago which changed the arguments to cmdable.Ping

**Comment by phutelmyer** [comment]
Thank you @deathnmind for posting this issue! 

Unsure why go-redis made that update, but I was able to implement [this fix](https://github.com/go-redis/redis/issues/1333#issuecomment-633171474) which has been tested and pushed into Master via [pull 137](https://github.com/target/strelka/pull/137)
