### ISSUE TITLE
Question - Yara scanning error?

### ISSUE THREAD

**Issue by markus-nclose** [target/strelka#158]
**Describe the bug**
Hi All. 
I'm not sure if I'm being a noob. I followed the install instructions and all is running and scanning fine. I however can't get Yara scanning working as all the files scanned produces the following:

```
 "yara": {
      "elapsed": 0.032276,
      "flags": [
        "compiling_error"
      ]
    }
```
I have downloaded the signature base from https://github.com/Neo23x0/signature-base and removed most yara rules to test. 
Am I missing something obvious?

**Steps to reproduce**
1. Default install docker
2. Map yara rules from Git repo mentioned to /etc/yara/
3. Run Filestream to send data from Suricata
4. See error above

**Expected behavior**
Yara output from scanned files?

**Release**
 Current latest Git clone

**Comment by markus-nclose** [comment]
Yes I was a noob. If you use that yara in other tools it will trow exceptions. (https://github.com/Neo23x0/signature-base#external-variables-in-yara-rules)

**Comment by phutelmyer** [comment]
@markus-nclose - Glad you were able to troubleshoot that. Let me know if I can help with any issues while you experiment with the tool. Happy you checked it out!

**Comment by Schi11ing** [comment]
Hello!
I have the same issue:
```
 "yara": {
      "elapsed": 0.032276,
      "flags": [
        "compiling_error"
      ]
    }
```

Steps to reproduce
Steps to reproduce the behavior:

    Default install docker
    Edit filestream config to add strelka-server IP and path to folder with files
    Run Filestream to send data from Suricata
    See error above

**Comment by markus-nclose** [comment]
Hi, 

What I did to find the yara file that was causing issues is to have a small python script to compile the files. It will throw an exception on the misbehaving yara file. 

You obviously need to install yara-python

```
#!/bin/python
import yara
import os

directory = r'/opt/yara/path/etc'
for entry in os.scandir(directory):
    if (entry.path.endswith(".yar")
            or entry.path.endswith(".yara")) and entry.is_file():
        yara.compile(entry.path)
```
