### ISSUE TITLE
PyMuPDF function xref_length doesn't exist in version 1.18.0

### ISSUE THREAD

**Issue by nighttardis** [target/strelka#198]
**Describe the bug**
When trying to run a PDF through Strelka with the current "build/python/backend/requiments.txt", PDF always fail with

`"pdf": {
            "elapsed": 0.000511,
            "flags": [
                "pdf_load_error"
            ],
            "total": {
                "extracted": 0,
                "objects": 0
            }
        },`

This is occurring because the function "xref_length" does not exist in PyMuPDF version 1.18.0

Reviewing the change history for the requirements.txt file it looks like the initial deployment of scan_pdf.py included PyMuPDF version 1.18.10, which does steam to have function. It also appears that on Aug 3rd 2021 the version was bumped to 1.18.15 and then downgrade to 1.18.0 instead of 1.18.10.

**Steps to reproduce**
1. Build the backend using the current "build" folder
2. Attempt to submit a PDF.

**Expected behavior**
Expectation that PDF are properly parsed.

**Screenshots**

**Release**
 - Release: [e.g. 1.19.05.16]

**Additional context**

**Comment by phutelmyer** [comment]
Thank you @nighttardis for the heads up. I'll likely be updating ScanPDF in the near future and I'll let you know when it's done testing.

**Comment by phutelmyer** [comment]
Should be fixed in #200
