### ISSUE TITLE
filestream staging directory created with 0755 permissions

### ISSUE THREAD

**Issue by cawalch** [target/strelka#213]
**Is your feature request related to a problem? Please describe.**

The `filestream` staging directory allows `r-x` for group and public users. 

https://github.com/target/strelka/blob/8b7e163d5c4da896c9599e12e8a21ae13ce84462/src/go/cmd/strelka-filestream/main.go#L118

**Describe the solution you'd like**
Can this be set to 0600 without causing issues (least privilege)?

**Comment by phutelmyer** [comment]
Good catch @cawalch. Seems like we can do with reduced privileges here. No need to execute from that staging directory...testing a PR now

**Comment by phutelmyer** [comment]
Fixed in #215
