### ISSUE TITLE
python-docx Python3.10 compatibility issue breaks docx parsing

### ISSUE THREAD

**Issue by asovern** [target/strelka#244]
**Describe the bug**
Utilizing the latest versions of Python3 and the python-docx module causes an error (`ImportError: cannot import name 'Sequence' from 'collections'`) due to incompatibility with Python3.10's renaming of `collections` to `collections.abc`.

**Steps to reproduce**
1. Build Strelka using Python3.10 (default for docker deployment)
3. Process a docx file type though the fileshot process
4. See error `ImportError: cannot import name 'Sequence' from 'collections'`

**Expected behavior**
File processes successfully and outputs results in log file

**Release**
 - Release: 0.22.12.08

**Additional context**
[Issue was raised](https://github.com/python-openxml/python-docx/issues/1151) on the official python-docx module repo in November, but has not received any interaction.

**Comment by phutelmyer** [comment]
@asovern This should be resolved per #245 submitted by @ryanohoro. Please reopen if you notice additional incompatability.
