### ISSUE TITLE
Invoke scanners based on yaraMetadata matches

### ISSUE THREAD

**Issue by infosec-intern** [target/strelka#26]
**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
I'd like a method for invoking scanners if custom YARA rules are matched. For example, if we have a rule that matches PE files with specific version info, and we want to send those samples to a malware sandbox.

I think adding a `yara` entry to the scanners config next to `flavors` would be a good way to control which rules trigger this behavior.

**Describe alternatives you've considered**
Querying our logs for all records matching xx YARA rule in yy timeframe, but this does not scale well at all.

**Additional context**
N/A

**Comment by jshlbrd** [comment]
I think this is a good idea and IIRC it is similar to the idea that @ksdahl had! Check this out: https://github.com/target/strelka/commit/65955318d3447802032bf2d97fbac571c7515daa

We used to only support one YARA flavors file, but now it can support any number of YARA files. My recommendation would be to load up that directory with however many YARA files you need, then you can reference the rules to load scanners in the Strelka config. For example, you could keep the default flavors.yara and add a file specifically for files you want sent to a sandbox. The Strelka config just needs to reference the YARA rule name to assign scanners.

**Comment by infosec-intern** [comment]
Aha ok, that clarifies quite a bit then. Great work @ksdahl! I was under the impression flavors were supposed to be for file types, but if the difference is actionable vs. non-actionable, then that's perfect. We'll use the system the way she intended too. I'll close this out and start testing that way.

**Comment by jshlbrd** [comment]
No worries! I think of flavors as being literally anything that describes a file, and that can be whatever makes the most sense for your deployment. The only consistent pattern with flavors in the public repo is that all file-related flavors end in "_file".
