### ISSUE TITLE
Unable to pip install on M1 MacBook

### ISSUE THREAD

**Issue by aaronherman** [target/strelka#268]
**Describe the bug**
When running `pip install -r src/python/requirements.txt` on an M1 Mac, I receive errors related to ssdeep, m2crypto, and PyMuPDF

**Comment by aaronherman** [comment]
**Work around**
m2crypto: https://gitlab.com/m2crypto/m2crypto/-/blob/master/INSTALL.rst
```
$ brew install openssl swig mupdf freetype cmake
$ LDFLAGS="-L$(brew --prefix openssl)/lib" \
CFLAGS="-I$(brew --prefix openssl)/include" \
SWIG_FEATURES="-I$(brew --prefix openssl)/include" \
pip install m2crypto
```

**Note**: this does not resolve the `ssdeep` issue.

**Comment by phutelmyer** [comment]
@aaronherman For this issue, would a recommendation be to add a new section to the pytest section of the docs to include M1 troubleshooting?

**Comment by phutelmyer** [comment]
It is no longer recommended to test the suite locally due to external dependencies needed for various scanners.
If you would like to test a scanner locally, please run `pytest` against that `test_*` file directly.
