### ISSUE TITLE
ScanBITS Failing to Import

### ISSUE THREAD

**Issue by ryanohoro** [target/strelka#305]
**Describe the bug**

ScanBITS cannot import the `bits` module and fails.

**Steps to reproduce**

```
docker-compose -f build/docker-compose.yaml exec backend bash
strelka@b6fb027d1ac2:/$  python -m strelka.scanners.scan_bits
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.10/dist-packages/strelka-0.0.0-py3.10.egg/strelka/scanners/scan_bits.py", line 9, in <module>
ModuleNotFoundError: No module named 'bits'
```

**Expected behavior**

Importing the scanner should not throw any exceptions.

```
strelka@b6fb027d1ac2:/$ python -m strelka.scanners.scan_bits
strelka@b6fb027d1ac2:/$ 
```

**Screenshots**

**Release**
 - Release:  0.23.01.07 

**Additional context**

**Comment by phutelmyer** [comment]
The dependency `bits_parser` was not set in `requirements.txt`.
By adding this dependency, the following dependency conflict is thrown:

```
#0 32.19 ERROR: Cannot install -r /strelka/requirements.txt (line 5) and construct==2.10.67 because these package versions have conflicting dependencies.
#0 32.19 
#0 32.19 The conflict is caused by:
#0 32.19     The user requested construct==2.10.67
#0 32.19     bits-parser 1.0.1 depends on construct==2.8.12
#0 32.19 
#0 32.19 To fix this you could try to:
#0 32.19 1. loosen the range of package versions you've specified
#0 32.19 2. remove package versions to allow pip attempt to solve the dependency conflict
```

While downgrading `construct` does fix this issue, `ScanLNK` will begin fail to parse files properly on that version of `construct`.

To fix this, the source package `bits_parser` needs to be updated to support more recent versions of `construct`.
This [source repository](https://github.com/ANSSI-FR/bits_parser) has not been updated in five years.

With these dependency issues, we are left with the following options:

- Identify / create new BITS parsing libraries to prevent downgrade need for `construct`
- Identify / create new LNK parsing libraries to allow downgrade of `construct`
- Remove ScanBits and associated libraries

**Comment by phutelmyer** [comment]
Closing per https://github.com/target/strelka/issues/305#issuecomment-1413023152

Please reopen if you have additional comments, or would like to discuss reinstating this scanner with fixes in mind.
