### ISSUE TITLE
[BUG] Tests do not complete successfully

### ISSUE THREAD

**Issue by weslambert** [target/strelka#347]
**Describe the bug**
It appears as though the tests do not complete successfully upon installation as described by the README. This prevents starting of the services.

```
#0 53.52 FAILED tests/test_scan_pcap.py::test_scan_pcap - AssertionError: {'elapsed': ...
#0 53.52 FAILED tests/test_scan_pcap.py::test_scan_pcap_ng - AssertionError: {'elapsed...
#0 53.52 ================= 2 failed, 121 passed, 20 warnings in 52.34s ==================
------
failed to solve: process "/bin/sh -c echo '[+] Run build checks' &&     cd /strelka/strelka/ &&     python3 -m pytest -p no:cacheprovider -s tests/ &&     if $CONFIG_TESTS; then python3 -m pytest -s tests_configuration/; fi &&     echo '[+] Done'" did not complete successfully: exit code: 1
```

**Environment details**
* Operating System: Ubuntu 22.04
* Architecture: 64bit

**Steps to reproduce**
1. Follow the steps in the README.

**Expected behavior**
Tests complete successfully and installation proceeds, or tests complete unsuccessfully and the user is provided the option to proceed anyway. Tests might not always indicate proper functioning, or may be limited to a small subset of functionality, so it would be nice to to have an option that still allows the platform to come up if tests fail. 

**Release**
 - Release: 0.23.01.07 (master)

**Comment by phutelmyer** [comment]
Able to replicate locally, with additional failures:
```
#0 104.7 -- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
#0 104.7 =========================== short test summary info ============================
#0 104.7 FAILED tests/test_scan_dmg.py::test_scan_dmg_compressed - AssertionError: {'e...
#0 104.7 FAILED tests/test_scan_dmg.py::test_scan_dmg_readonly - AssertionError: {'ela...
#0 104.7 FAILED tests/test_scan_dmg.py::test_scan_dmg_readwrite - AssertionError: {'el...
#0 104.7 FAILED tests/test_scan_pcap.py::test_scan_pcap - AssertionError: {'elapsed': ...
#0 104.7 FAILED tests/test_scan_pcap.py::test_scan_pcap_ng - AssertionError: {'elapsed...
#0 104.7 FAILED tests/test_scan_seven_zip.py::test_scan_sevenzip - AssertionError: {'e...
#0 104.7 FAILED tests/test_scan_seven_zip.py::test_scan_sevenzip_wordlist - AssertionE...
#0 104.7 FAILED tests/test_scan_seven_zip.py::test_scan_sevenzip_wordlist_filenames - ...
#0 104.7 FAILED tests/test_scan_seven_zip.py::test_scan_sevenzip_nocrack_filenames - A...
#0 104.7 FAILED tests/test_scan_seven_zip.py::test_scan_sevenzip_brute - AssertionErro...
#0 104.7 FAILED tests/test_scan_vhd.py::test_scan_vhd - AssertionError: {'elapsed': <A...
#0 104.7 FAILED tests/test_scan_vhd.py::test_scan_vhdx - AssertionError: {'elapsed': <...
#0 104.7 ============ 12 failed, 90 passed, 28 warnings in 104.00s (0:01:44) ============
```

**Comment by phutelmyer** [comment]
I'm able to build off the most recent commits, which leads me to believe this is an issue with outdated dependencies or packages. I will put together and test a new release today.

**Comment by weslambert** [comment]
Thanks, Paul!

**Comment by phutelmyer** [comment]
@weslambert - Release https://github.com/target/strelka/releases/tag/0.23.03.14 is now available. This _should_ work fine.

In addition, https://github.com/target/strelka/pull/348 was created to reduce the need for users to build local images for testing. I'll add that to the documentation / README and merge in shortly.

**Comment by weslambert** [comment]
Great! Thanks, Paul! I agree that using the pre-built images will reduce the time to stand up the platform and likely reduce the number of issues users may run into as a result of their local configuration or commits since release.

**Comment by phutelmyer** [comment]
In addition to the fix in https://github.com/target/strelka/releases/tag/0.23.03.14, prebuilt images are now available. Previously troublesome tests have also been commented out.
