### ISSUE TITLE
.deb/.rpm Package Support 

### ISSUE THREAD

**Issue by zachsis** [target/strelka#36]
**Is your feature request related to a problem? Please describe.**
Considering the number of dependencies this project has, it would be beneficial for the project to have stable releases maintained in .deb/.rpm packages. I believe this would also allow for wider adoption of the project being that it would add an ease-of-use / better user experience to get up and running with strelka. 

**Describe the solution you'd like**
RPM support in EPEL,  DEB Support in `$ubuntu_package_repo_here` 

**Describe alternatives you've considered**
There is no alternative, there is only zuul. In all seriousness though, I think the alternative is what we are all doing now which is building the package + dependencies from source. 

**Additional context**
This discussion came up on the project slack channel. It was recommended we place this as an issue for tracking if anyone in the community wants to try and tackle the feature request.

**Comment by jshlbrd** [comment]
Good idea -- I've marked this as a good first issue because anyone with experience building packages would be able to do this. 

The other alternative not mentioned is running the system as a Docker container.

**Comment by jshlbrd** [comment]
Marking as wontfix -- the new architecture migrates us to containers and we don't plan to support native OS installs.
