### ISSUE TITLE
[BUG] Cannot install Strelka 0.23.03.14 UI component

### ISSUE THREAD

**Issue by ForensicITGuy** [target/strelka#376]
**Describe the bug**
While following the quickstart and server installation instructions, Strelka does not build and run due to an error when trying to pull the image for the UI component.

**Environment details**
* Operating System: Ubuntu 22.04
* Architecture: X86_64

**Steps to reproduce**
1. Clone strelka repo or release package
2. run `docker-compose -f build/docker-compose.yaml up -d`

**Expected behavior**
Strelka to build and run

**Screenshots**
![image](https://github.com/target/strelka/assets/8247090/5b24a19f-cafe-4930-a358-52b644d8628f)

**Release**
 - Release: 0.23.03.14
 - Also tried with the current version in the repo later than release but got the same message with a different number on the end

**Additional context**
I suspect this is an issue with the permissions of the UI component container image entry in its repository.

**Comment by phutelmyer** [comment]
Hey @ForensicITGuy - apologies for that. You're correct, permissions are required to access `ghcr.io`. I switched all the images to `docker hub` per #377 to avoid that moving forward.

Let me know if that helps!
