### ISSUE TITLE
[BUG] Strelka UI not showing submissions

### ISSUE THREAD

**Issue by derfel1989** [target/strelka#393]
I'm submitting the file through the UI, but it isn't showing in the submission list. The docker installation is fresh.

![image](https://github.com/target/strelka/assets/46175778/68a35379-dc93-49ba-8ea5-971db51a1130)

I noticed some errors in the Postgres logs for each submission.

![image](https://github.com/target/strelka/assets/46175778/16a5ae07-6055-4e0e-ae01-eaccbfbd9a94)

The file /var/lib/docker/volumes/strelka_logs/_data/**strelka.log** shows the scan JSON result.

Thank you.

**Comment by derfel1989** [comment]
@ryanohoro, any clue? = )

**Comment by ryanohoro** [comment]
Strelka UI is not within my expertise in the project. We'll have to defer to @phutelmyer on this one.

**Comment by phutelmyer** [comment]
@derfel1989, I've noticed this with a few files in the past. As I see that you did have a successful file submission prior to this, the issue here is that the UI isn't processing a specific file properly.

Either the UI or Strelka backend is missing proper error handling. 

Is it possible for you to share the file or content that you're attempting to submit?

**Comment by derfel1989** [comment]
@phutelmyer thank you for your time. Almost all files submitted aren't showing up in the UI.

Attached is the file requested.

- XLS file - 
[securelist_united states of america_on-access-scan_month_2022-02-25.xlsx](https://github.com/target/strelka/files/12397149/securelist_united.states.of.america_on-access-scan_month_2022-02-25.xlsx)

Thank you.

**Comment by phutelmyer** [comment]
Working on a local instance for me, but I'll test it using the same configuration as I will use in #394

**Comment by phutelmyer** [comment]
I was able to replicate this issue using the latest image from Dockerhub. I will attempt to troubleshoot this.

**Comment by derfel1989** [comment]
@phutelmyer thank you for your time. Unfortunately, almost all files submitted aren't showing in the UI.

Could you share dockerhub repo link?

**Comment by phutelmyer** [comment]
@derfel1989 - Strelka-UI has been updated. Please pull the latest repo change or pull the latest docker image to test out this change.

**Comment by phutelmyer** [comment]
This should be resolved in the [latest release of the Strelka UI](https://github.com/target/strelka-ui/releases/tag/v1.52) which should be pulled when building Strelka.

**Comment by derfel1989** [comment]
Many thanks!

> This should be resolved in the [latest release of the Strelka UI](https://github.com/target/strelka-ui/releases/tag/v1.52) which should be pulled when building Strelka.
