### ISSUE TITLE
[BUG] Login failed when UI is under port 443

### ISSUE THREAD

**Issue by derfel1989** [target/strelka#414]
**Describe the bug**
I can only have port 443 enabled. So, I changed the Strelka UI port from 8080 to 443. However, after a couple of hours, I received the warning "Login Failed" at the top when I tried to access the website.

**Environment details**
* Operating System: Ubuntu 22.04 / Docker / Portainer

**Steps to reproduce**
Change host port to 443 keeping the docker port 8080

`    ports:
      - "443:8080"`

**Expected behavior**
Successful login.

**Screenshot**

<a href="https://ibb.co/t3s1Q1q"><img src="https://i.ibb.co/t3s1Q1q/msedge-FSd14-W4kf1.png" alt="msedge-FSd14-W4kf1" border="0"></a>

<a href="https://ibb.co/JKFNp2W"><img src="https://i.ibb.co/JKFNp2W/msedge-m-JMe-MFZdon.png" alt="msedge-m-JMe-MFZdon" border="0"></a>

**Release**
 - Release: [latest]

**Additional context**
N/A

**Comment by phutelmyer** [comment]
@derfel1989 - Apologies for the delay here. I'm encountering a similar inability to login with the latest release. Not sure that's related to your port issue, but I'm currently troubleshooting it.

**Comment by phutelmyer** [comment]
@derfel1989, 

[Strelka-UI](https://github.com/target/strelka-ui) has been updated with a bug fix. Not sure this will fix your issue, but it fixed a related issue for me. When bringing the cluster up, please ensure that you have the latest version of the [Strelka-UI] Image(https://hub.docker.com/layers/target/strelka-ui/latest/images/sha256-35d3d01a8d28613dc7195fc75c49599277a13de8791313fb1f23f67278374d6c?context=explore)

Please reopen this ticket if you seem to still be having issues.
