### ISSUE TITLE
[BUG] ScanPe adds dictionary to flags array

### ISSUE THREAD

**Issue by andrea-matsec** [target/strelka#433]
**Describe the bug**
I'm not sure if this is a bug or an intentional change, but it seems  that ScanPe adds a dictionary to the flags array under certain conditions. 
I was able to identify the commit causing this change in behavior https://github.com/target/strelka/commit/6aec6d622494baa0eb0578f5fba162a9718ed945#diff-8ab020f57ff0fffcfc6278539ec45f71021c8000ee44e3aa7a978fc13abaa976
and I was wondering if it was intentional to change the condition form
```
        if cert_dict := parse_certificates(data):
            if type(cert_dict) != str:
                self.event["security"] = cert_dict
            else:
                self.flags.append(cert_dict)
 ```
to
```
        if cert_dict := parse_certificates(data):
            if type(cert_dict) is str:
                self.event["security"] = cert_dict
            else:
                self.flags.append(cert_dict)
```
instead of 
```
        if cert_dict := parse_certificates(data):
            if type(cert_dict) is not str:
                self.event["security"] = cert_dict
            else:
                self.flags.append(cert_dict)
```

**Comment by phutelmyer** [comment]
@andrea-matsec Thank you so much for identifying this! I definitely don't want to use that field for a dictionary. I'll fix that up and get that changed today. Really appreciate it. :)
