### ISSUE TITLE
Strelka unittest files repo

### ISSUE THREAD

**Issue by infosec-intern** [target/strelka#48]
**Is your feature request related to a problem? Please describe.**
After writing a few more test files, I've realized it's much easier to host files in a repository rather than pulling them down in each test. I've created a repo ([strelka_test_files](https://github.com/infosec-intern/strelka_test_files)) and want your opinion on moving forward with it.

**Describe the solution you'd like**
If the repository of test files is fine with you, I'd like to transfer/recreate it under the Target origanization just to keep everything in line with the project. I've refactored the PE scanner test to use this repository, and written a few more scanner tests that use it as well, which you can find on [my org's page](https://github.com/CenturyLinkGlobalCyberDefense/strelka/commits/tests)

**Describe alternatives you've considered**
Currently, the PE scanner test dynamically pulls a specific version of Putty down to perform tests on, but:
* the added network call potentially makes the tests unacceptably slow depending on network speed - this will only compound with more tests regardless of network speeds
* the Putty link is not guaranteed to be up forever (whereas I'm assuming if someone can get to the `strelka` GitHub repo they can get to a `strelka_test` repo)
* it has been difficult to find test files hosted on the internet with permanent links and for all the needed test scenarios

**Additional context**
N/A

**Comment by jshlbrd** [comment]
Good idea! This should be fine, but let me chat with our Git team to see what they think. Generally Git isn’t great at tracking binary data, so I’d prefer to leave the decision and any potential alternatives up to them.

**Comment by jshlbrd** [comment]
Still working out the details on this! I'll update again once we have it figured out.

**Comment by jshlbrd** [comment]
I feel like a total Git n00b for not thinking of this before, but have you thought about Git LFS? https://git-lfs.github.com/

We may need to test this on a forked repo, but this could be a good solution to keep everything integrated into this repo.

**Comment by infosec-intern** [comment]
I haven't messed with that before, but I can certainly give it a shot on my fork 👍

**Comment by infosec-intern** [comment]
You may need to examine this more closely first; I'm unable to push LFS objects to my strelka fork without them being enabled on the parent repository. See: https://github.com/git-lfs/git-lfs/issues/1449

On the bright side, LFS does look like it would suit our use case. Here's a sample commit for putty.exe
```txt
version https://git-lfs.github.com/spec/v1
oid sha256:81de431987304676134138705fc1c21188ad7f27edf6b77a6551aa693194485e
size 774200
```

**Comment by jshlbrd** [comment]
Take a look at this branch and let me know if this works for you: https://github.com/target/strelka/tree/lfs-test

**Comment by infosec-intern** [comment]
Sorry for the extended silence on this. 

I was able to use LFS on my own test_files repository and it is pretty easy. Unfortunately, when I tried getting this working using your branch as my base I got the same error about pushing to a public fork. 

Ultimately, I do think LFS is a good strategy for the test files. Since I can't push my files directly up to your repo I can keep working on the unit tests and then share the files with you later on when I have a more substantial portion of the tests done. What do you think?

**Comment by jshlbrd** [comment]
No problem, and your plan sounds good -- any time you're ready to bring some files and tests in, just let me know.

**Comment by dcode** [comment]
did this go anywhere? looks like the originally linked repo is gone now

**Comment by phutelmyer** [comment]
As the original repository has since been closed, and it has been quite some time since any comments, I will be closing this. If anyone would like to reboot this effort, feel free to reopen this issue and we can start a discussion.

Thanks!
