### ISSUE TITLE
Go client

### ISSUE THREAD

**Issue by jshlbrd** [target/strelka#5]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
It'd be nice to see a working Go client. I'm not sure what the state of ZMQ support in Go is, but that should be the only technical roadblock.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by zerstoeren** [comment]
I'm not sure what kind of time I have, but what would the requirements be for the Go client if I found time.  I'm booked up through the holidays, but might have a few moment here an there after the holidays.

**Comment by jshlbrd** [comment]
Thanks for the offer! These would be the minimum requirements:
- Uses ZeroMQ Push socket (with optional CurveMQ support) for sending messages
- Messages are formatted according to the documented protobuf
- Able to accept a file, directory, or URL as input

Those requirements would make the Go client functionally equivalent to the Python user client. Ideally other Go clients could be based off of this client — for example, a functionally equivalent Go dirstream client would need to monitor a directory for new files in real-time. Adding Go support to the client library would go a long way to making this code reusable.

**Comment by jshlbrd** [comment]
Marking this as wontfix -- the gRPC has Go clients that will be published in a separate repository. If for some reason we do not migrate to gRPC, then I'll reopen this.

**Comment by zerstoeren** [comment]
@jshlbrd I apologize.  I have been offline with a chronically sick 3 year old for a bit.  I haven't had a chance to look at this yet though.

**Comment by jshlbrd** [comment]
@zerstoeren don't worry about it (and best of luck) -- we'll revisit this later once the gRPC migration is worked out.

**Comment by zerstoeren** [comment]
@jshlbrd thanks.  Let me know.  Would love to contribute once things calm down.
